// Original BuzzFeed-listicle-style categories, written fresh for this app
// (not transcribed from any physical game's card text).
export const CATEGORIES: string[] = [
  'Hot Dads',
  'Things That Deserve A Round Of Applause Just For Existing',
  'Celebrities You’d Let Ruin Your Life',
  'Insults That Don’t Contain A Curse Word',
  'Random Things That Are Weirdly Addictive',
  'Times A Celebrity Was Actually Your Favorite Person',
  'Questions You’re Too Afraid To Ask',
  'Movie Plot Holes That Still Bother Us',
  'Things That Are Somehow Still Legal',
  'Signs You Peaked In High School',
  'Foods That Are Better Cold Than Hot',
  'Things Nobody Asked For But We Got Anyway',
  'Excuses That Never Actually Work',
  'Things That Get Weirdly Competitive',
  'Objects That Should Not Be Sentient But Kind Of Are',
  'Things You’d Bring To A Deserted Island For No Reason',
  'Reasons To Leave A Group Chat',
  'Things That Sound Fake But Are Real',
  'Celebrities Who Seem Like They’d Give Bad Advice',
  'Things That Peaked In The 2000s',
  'Jobs That Sound Made Up',
  'Things That Are Weirdly Satisfying To Watch',
  'Reasons Someone Might Ghost You',
  'Things That Are Only Acceptable On Vacation',
  'Animals That Would Win In A Fight Against A Toddler',
  'Things That Are Secretly A Personality Type',
  'Snacks That Cause Arguments',
  'Things You’d Regret Saying In A Toast',
  'Household Items That Could Be Weapons In A Pinch',
  'Things That Are Somehow Both Impressive And Sad',
  'Reasons To Fake A Phone Call',
  'Things That Get Ruined By Overexplaining',
  'Celebrities Who Seem Like Bad Roommates',
  'Things That Are Way Scarier Than They Should Be',
  'Signs Someone Is About To Do Something Dumb',
  'Things That Should Come With A Warning Label',
  'Foods That Don’t Deserve Their Reputation',
  'Things That Are Impressive For The Wrong Reasons',
  'Reasons A Party Actually Ends',
  'Things That Are Way More Complicated Than They Look',
  'Objects That Have Definitely Been Used As A Weapon In A Movie',
  'Things That Instantly Age You',
  'Words That Sound Made Up But Aren’t',
  'Things That Are Suspiciously Specific',
  'Reasons Not To Trust Someone',
  'Things That Are Only Funny At 2AM',
  'Celebrities Who Could Probably Beat You Up',
  'Things That Are A Red Flag On A First Date',
  'Places You’d Hide If Something Chased You',
  'Things People Lie About On Dating Apps',
  'Sounds That Instantly Stress You Out',
  'Things That Are Deceptively Difficult',
  'Reasons To Cancel Plans Last Minute',
  'Things That Are Weirdly Emotional For No Reason',
  'Celebrities Who’d Be Terrible At Parenting',
  'Things That Are Impossible To Do Quietly',
  'Objects That Are Scarier In The Dark',
  'Things That Should Be Illegal But Aren’t',
  'Reasons A Group Project Falls Apart',
  'Things That Get Better With Age (Besides Wine)',
  'Signs You’re The Problem In The Group Chat',
  'Things That Are Wildly Overpriced For No Reason',
  'Foods That Are Just An Excuse To Eat Sauce',
];
