// Original, adult-humor category pool — written fresh for this app in a Cards Against
// Humanity-adjacent voice (not transcribed from any physical game's card text). Only
// used when a player explicitly enables Raunchy Mode in Settings; family-friendly
// CATEGORIES in categories.ts remain the default.
export const CATEGORIES_ADULT: string[] = [
  'Things You Shouldn’t Say During Sex',
  'Worst Pickup Lines Ever',
  'Signs Your Tinder Date Is A Red Flag',
  'Things That Are Way Better In Theory Than In Bed',
  'Nicknames For Body Parts You’d Never Say Out Loud',
  'Terrible Excuses For A One Night Stand',
  'Things You Lie About On A First Date',
  'Signs You’re Definitely Getting Ghosted',
  'Bad Ideas After Three Tequila Shots',
  'Things That Ruin The Mood Instantly',
  'Weird Noises People Make During Sex',
  'Questions You Should Never Ask An Ex',
  'Things You’d Never Admit To Your Mom',
  'Red Flags Disguised As Green Flags',
  'Signs Someone Is Bad In Bed',
  'Things People Fake',
  'Awkward Things To Yell During Sex',
  'Signs Your Relationship Is On The Rocks',
  'Things You Shouldn’t Text Your Ex At 2AM',
  'Bad Places To Have Sex',
  'Things That Sound Dirty But Aren’t',
  'Things That Aren’t Dirty But Sound Like They Are',
  'Signs You Might Be The Toxic One',
  'Worst Things To Find On Your Partner’s Phone',
  'Things You Regret Saying Mid-Orgasm',
  'Bad Nicknames For Your Private Parts',
  'Signs A Situationship Has Gone On Too Long',
  'Things People Lie About On Dating Apps',
  'Reasons Your Date Left Early',
  'Worst Things To Say Right After Sex',
  'Things You Shouldn’t Google While Drunk',
  'Bad Times To Get A Boner',
  'Things That Kill The Mood Instantly',
  'Signs Your Friends With Benefits Wants More',
  'Worst Times For A Wardrobe Malfunction',
  'Things You’d Never Say To Your In-Laws',
  'Signs Of A Bad Hookup',
  'Things You Do Right After A Walk Of Shame',
  'Bad Excuses For Missing Your Own Wedding Night',
  'Things That Happen In A Cheap Motel Room',
  'Signs You’re About To Get Dumped',
  'Worst Things To Whisper In Someone’s Ear',
  'Things You’d Never Say During A Threesome',
  'Signs You Should Not Be Someone’s Rebound',
  'Bad Combinations Of Body Parts And Nicknames',
  'Things That Are Weirdly Erotic',
  'Signs Your Ex Is Stalking Your Instagram',
  'Worst Things To Say To A Stripper',
  'Things You’d Regret Doing On Spring Break',
  'Signs A Hall Pass Went Too Far',
  'Bad Things To Say During A Booty Call',
  'Things People Do In The Bathroom At A Party',
  'Signs You’ve Been “Netflix And Chilling” Too Long',
  'Worst Nicknames A Partner Has Called You',
  'Things You’d Never Confess During Truth Or Dare',
  'Signs You Should Not Reply To That Text',
  'Bad Reasons To Get Back Together',
  'Things That Happen In The Group Chat After A Breakup',
  'Signs You’re The Side Piece',
  'Worst Things To Say On A Blind Date',
  'Bad Decisions Made After Midnight',
  'Things You Do When You’re Way Too Drunk',
  'Worst Hangover Cures',
  'Things You Regret Ordering At 3AM',
  'Bad Ideas That Start With “Hold My Beer”',
  'Signs You Blacked Out Last Night',
  'Things You Find In Your Pockets The Morning After',
  'Worst Things To Do At An Open Bar',
  'Signs The Party Has Gone Too Far',
  'Things You Text When You’re Drunk',
  'Bad Excuses For Missing Work After A Big Night',
  'Worst Things To Say In A Drunk Voicemail',
  'Signs You Peaked At Karaoke',
  'Things That Happen At A Bachelor Party',
  'Bad Ideas For A Drinking Game',
  'Signs Someone Had Way Too Much Tequila',
  'Worst Things To Do At A Wedding Open Bar',
  'Things You Regret Doing On A Bar Crawl',
  'Signs You’re The Drunkest Person At The Party',
  'Bad Karaoke Song Choices',
  'Things You Find On Your Phone The Morning After',
  'Worst Things To Yell At A Bar',
  'Signs It’s Time To Cut Someone Off',
  'Bad Ideas For A Bachelorette Party',
  'Things You Do At 4AM In A Diner',
  'Worst Things To Bring To A Kegger',
  'Signs You Need An Intervention',
  'Things That Happen In A Vegas Hotel Room',
  'Bad Excuses For A Hangover',
  'Worst Things To Say While Doing Shots',
  'Signs You’re About To Get Kicked Out Of The Bar',
  'Things You Regret Doing At An Office Party',
  'Bad Ideas That Seem Great After A Few Drinks',
  'Signs You Overdid It At Happy Hour',
  'Worst Things To Post After A Night Out',
  'Bad Excuses For Drunk Dialing Your Boss',
  'Signs You Need To Go Home Immediately',
  'Worst Things To Say To A Bartender',
  'Things That Happen During Beer Pong',
  'Things That Are Weirdly Satisfying To Pop',
  'Sounds Your Body Makes That You Can’t Control',
  'Worst Places To Have Gas',
  'Things You Do When Nobody’s Watching',
  'Bad Times For Your Stomach To Growl',
  'Signs You Need To See A Doctor But Won’t',
  'Things You’d Never Admit To Doing In The Shower',
  'Worst Bodily Functions To Have In Public',
  'Things That Happen After Late-Night Fast Food',
  'Bad Smells You Blame On The Dog',
  'Signs You Ate Something That Disagreed With You',
  'Things You Do In The Bathroom That Take Way Too Long',
  'Signs Of A Bad Gym Session',
  'Things You’d Never Say Out Loud About Your Body',
  'Things That Happen When You Hold It In Too Long',
  'Worst Smells In A Locker Room',
  'Signs You Need To Change Your Underwear',
  'Things You Do When You Think You’re Alone',
  'Bad Excuses For A Weird Smell',
  'Things That Happen After Taco Tuesday',
  'Worst Things To Sneeze During',
  'Signs Your Diet Is Not Working',
  'Things You’d Never Want Overheard From The Bathroom',
  'Bad Times To Fart',
  'Worst Sounds A Body Can Make',
  'Signs You Should Not Have Eaten That',
  'Things You Do That Are Secretly Gross',
  'Things You’d Never Say In A Job Interview',
  'Worst Things To Reply-All On Accident',
  'Signs You Hate Your Job',
  'Things You Do During A Boring Meeting',
  'Bad Excuses For Being Late To Work',
  'Signs Your Coworker Has A Crush On You',
  'Things You’d Never Tell HR',
  'Worst Office Party Behavior',
  'Signs You’re About To Get Fired',
  'Things You Do In The Office Bathroom',
  'Bad Ideas For A Work Happy Hour',
  'Signs Of A Workplace Situationship',
  'Things You’d Never Say To Your Boss’s Face',
  'Worst Things To Overhear In The Break Room',
  'Signs You Peaked At The Company Retreat',
  'Things You Do When You’re Bored At Work',
  'Bad Excuses For Missing A Deadline',
  'Signs Your Work Crush Is Mutual',
  'Things You’d Never Admit To Googling At Work',
  'Worst Things To Say In A Performance Review',
  'Signs You Need A New Job',
  'Things That Happen In The Supply Closet',
  'Bad Ideas For An Office Prank',
  'Signs You’re The Office Gossip',
  'Things You’d Never Wear To A Job Interview',
  'Worst Zoom Call Mishaps',
  'Signs Your Coworker Overshares',
  'Things You Do To Avoid Your Boss',
  'Bad Excuses For Leaving Early',
  'Things You’d Never Say In A Work Email',
  'Things You’d Never Say At Thanksgiving Dinner',
  'Worst Things To Bring Up At A Family Reunion',
  'Signs Your Family Has Too Many Secrets',
  'Things You’d Never Tell Your Parents',
  'Bad Excuses For Missing A Family Event',
  'Signs You’re The Black Sheep Of The Family',
  'Things You’d Never Say In Front Of Grandma',
  'Worst Things To Overhear Your Parents Say',
  'Signs A Family Dinner Is About To Go Wrong',
  'Things You’d Never Admit To Your Siblings',
  'Bad Ideas For A Family Vacation',
  'Signs Your In-Laws Don’t Like You',
  'Things You’d Never Say At A Baby Shower',
  'Worst Things To Say At A Funeral',
  'Signs You Overshared At Book Club',
  'Things You’d Never Tell Your Therapist',
  'Bad Excuses For A Family Fight',
  'Signs You’re The Favorite Child (Or Not)',
  'Things You’d Never Say To A Cop',
  'Worst Things To Say During A Toast',
  'Signs Your Neighbor Knows Too Much',
  'Things You’d Never Admit To A Stranger',
  'Bad Ideas For A Group Chat Name',
  'Signs You’re Oversharing On Social Media',
  'Worst Things To Text The Wrong Person',
  'Signs You’re About To Get Called Out',
  'Things You’d Never Confess In A Game Of Truth Or Dare',
  'Bad Excuses For A Missed Call',
  'Things You’d Never Say At A PTA Meeting',
  'Bad Excuses For Being “Tired” At Work',
  'Signs Someone’s Had Too Much Weed',
  'Things You Do After One Too Many Edibles',
  'Worst Munchies Choices',
  'Signs You’re About To Get A Contact High',
  'Things You’d Never Admit To Your Dealer',
  'Bad Ideas While Stoned',
  'Signs You Overdid It At A Music Festival',
  'Things That Happen At 4:20',
  'Worst Excuses For Red Eyes',
  'Signs You Need To Lay Off The Vape',
  'Things You Do When You’re Way Too High',
  'Bad Ideas For A College Party',
  'Signs You’ve Had Too Much Caffeine (And Also Weed)',
  'Things That Are Inappropriately Named',
  'Euphemisms That Are Secretly About Sex',
  'Things You’d Never Put In A Wedding Speech',
  'Worst Things To Say During A Massage',
  'Signs You’ve Watched Too Much Reality TV',
  'Things That Sound Like Sex Toys But Aren’t',
  'Bad Names For A Strip Club',
  'Signs Your Roommate Is Too Loud At Night',
  'Things You’d Never Say To Airport Security',
  'Worst Things To Bring To A Sleepover As An Adult',
  'Signs You’re Too Old For This',
  'Things You’d Never Admit To Your Yoga Instructor',
  'Bad Excuses For A Walk Of Shame',
  'Signs You Need Better Boundaries',
  'Things That Happen At A Nude Beach',
  'Signs You’ve Overshared On A First Date',
  'Things You’d Never Say To A Priest',
  'Bad Ideas For A Tattoo',
  'Signs Your Filter Is Broken',
  'Things You’d Never Say On A Family Group Chat',
  'Worst Things To Autocorrect Into',
  'Signs You Need To Log Off Social Media',
  'Things That Are Funnier When Said By A Grandma',
  'Bad Excuses For Ghosting Someone',
  'Signs You’re A Bad Influence',
  'Things You’d Never Admit At A Support Group',
  'Worst Things To Say During Jury Duty',
  'Signs You Overdid It At The Casino',
  'Things That Happen On A Cruise Ship After Dark',
  'Worst Things To Say To Your Landlord',
  'Signs You’ve Overstayed Your Welcome',
  'Things That Happen At A Swingers Party (Allegedly)',
  'Bad Excuses For Being Naked',
  'Signs You Should Not Be A Wingman',
  'Things You’d Never Say To A Hairdresser',
  'Worst Things To Say In A Wedding Toast',
  'Signs You’re The Reason The Group Chat Went Quiet',
  'Things That Happen At An All-Inclusive Resort',
  'Bad Ideas For A Second Date',
  'Signs Your “Business Trip” Story Doesn’t Add Up',
  'Things You’d Never Say To A Chiropractor',
  'Worst Things To Hear Through A Hotel Wall',
  'Signs You’re Bad At Flirting',
  'Things That Are Weirdly Competitive Between Couples',
  'Bad Excuses For A Hickey',
  'Signs You’ve Been Talking To A Catfish',
  'Things You’d Never Say To A Personal Trainer',
  'Worst Things To Say During A Prostate Exam',
  'Signs You Need To Delete The App',
  'Things That Happen During A Messy Divorce',
  'Bad Ideas For A Honeymoon',
  'Signs You’re Emotionally Unavailable',
  'Things You’d Never Say To A Bouncer',
  'Worst Things To Say At A Bridal Shower',
  'Signs You’re The Reason Nobody Trusts You With Secrets',
  'Things That Happen At A College Reunion',
  'Bad Excuses For Skipping Date Night',
  'Signs You’re Bad At Sexting',
  'Things You’d Never Say To A Divorce Lawyer',
  'Worst Things To Say In A Toast At Your Own Wedding',
  'Signs You Peaked In Your Situationship Era',
  'Things That Happen At A Frat Party',
  'Bad Excuses For A Missed Anniversary',
  'Signs You’ve Been Love-Bombed',
  'Things You’d Never Say To A Sex Therapist',
  'Worst Things To Say During A Lap Dance',
  'Signs You’re The Villain In Someone Else’s Story',
  'Things That Happen At An Adult Prom',
  'Bad Ideas For A Roommate Rule',
  'Signs You’re Too Comfortable With Your Roommate',
  'Things You’d Never Say To A Gynecologist',
  'Worst Things To Say During A Colonoscopy',
  'Signs You Need To Set An Alarm For The Walk Of Shame',
  'Things That Happen At A Nudist Resort',
  'Bad Excuses For A Broken Bed Frame',
  'Signs You’re In A Situationship Loop',
  'Things You’d Never Say To A Wedding Officiant',
  'Worst Things To Overhear At A Sperm Bank',
  'Signs You’ve Peaked At Sending Nudes',
  'Things That Happen During A Bad Breakup',
  'Bad Ideas For A Group Sext',
  'Signs Your DMs Have Gone Too Far',
  'Things You’d Never Say To A Marriage Counselor',
  'Worst Things To Say During A Pap Smear',
  'Signs You’ve Overstayed A One Night Stand',
  'Things That Happen At A Key Party',
  'Bad Excuses For A Lipstick Stain',
  'Signs You’re Bad At Reading The Room',
  'Things You’d Never Say To A Bartender On Your Wedding Day',
  'Worst Things To Say During Speed Dating',
  'Things You’d Never Say To A Notary',
  'Worst Things To Say At A Christening',
  'Signs You’ve Overshared At A Baby Shower',
  'Things That Happen At A Timeshare Presentation',
  'Bad Excuses For A Missed Curfew (As An Adult)',
  'Signs You’re Too Old For Spring Break',
  'Things You’d Never Say To A Life Coach',
  'Worst Things To Say During A Job Reference Call',
  'Signs You Peaked At A House Party',
  'Things That Happen At A Silent Disco',
  'Bad Ideas For A Roast',
];
