// Original BuzzFeed-listicle-style categories, written fresh for this app
// (not transcribed from any physical game's card text).
export const CATEGORIES: string[] = [
  'Hot Dads',
  'Things That Deserve A Round Of Applause Just For Existing',
  'Celebrities You’d Let Ruin Your Life',
  'Insults That Don’t Contain A Curse Word',
  'Random Things That Are Weirdly Addictive',
  'Times A Celebrity Was Actually Your Favorite Person',
  'Questions You’re Too Afraid To Ask',
  'Movie Plot Holes That Still Bother Us',
  'Things That Are Somehow Still Legal',
  'Signs You Peaked In High School',
  'Foods That Are Better Cold Than Hot',
  'Things Nobody Asked For But We Got Anyway',
  'Excuses That Never Actually Work',
  'Things That Get Weirdly Competitive',
  'Objects That Should Not Be Sentient But Kind Of Are',
  'Things You’d Bring To A Deserted Island For No Reason',
  'Reasons To Leave A Group Chat',
  'Things That Sound Fake But Are Real',
  'Celebrities Who Seem Like They’d Give Bad Advice',
  'Things That Peaked In The 2000s',
  'Jobs That Sound Made Up',
  'Things That Are Weirdly Satisfying To Watch',
  'Reasons Someone Might Ghost You',
  'Things That Are Only Acceptable On Vacation',
  'Animals That Would Win In A Fight Against A Toddler',
  'Things That Are Secretly A Personality Type',
  'Snacks That Cause Arguments',
  'Things You’d Regret Saying In A Toast',
  'Household Items That Could Be Weapons In A Pinch',
  'Things That Are Somehow Both Impressive And Sad',
  'Reasons To Fake A Phone Call',
  'Things That Get Ruined By Overexplaining',
  'Celebrities Who Seem Like Bad Roommates',
  'Things That Are Way Scarier Than They Should Be',
  'Signs Someone Is About To Do Something Dumb',
  'Things That Should Come With A Warning Label',
  'Foods That Don’t Deserve Their Reputation',
  'Things That Are Impressive For The Wrong Reasons',
  'Reasons A Party Actually Ends',
  'Things That Are Way More Complicated Than They Look',
  'Objects That Have Definitely Been Used As A Weapon In A Movie',
  'Things That Instantly Age You',
  'Words That Sound Made Up But Aren’t',
  'Things That Are Suspiciously Specific',
  'Reasons Not To Trust Someone',
  'Things That Are Only Funny At 2AM',
  'Celebrities Who Could Probably Beat You Up',
  'Things That Are A Red Flag On A First Date',
  'Places You’d Hide If Something Chased You',
  'Things People Lie About On Dating Apps',
  'Sounds That Instantly Stress You Out',
  'Things That Are Deceptively Difficult',
  'Reasons To Cancel Plans Last Minute',
  'Things That Are Weirdly Emotional For No Reason',
  'Celebrities Who’d Be Terrible At Parenting',
  'Things That Are Impossible To Do Quietly',
  'Objects That Are Scarier In The Dark',
  'Things That Should Be Illegal But Aren’t',
  'Reasons A Group Project Falls Apart',
  'Things That Get Better With Age (Besides Wine)',
  'Signs You’re The Problem In The Group Chat',
  'Things That Are Wildly Overpriced For No Reason',
  'Foods That Are Just An Excuse To Eat Sauce',
  'Things That Are Way Louder Than They Need To Be',
  'Celebrities Who Seem Like They Smell Like Money',
  'Things You’d Never Admit To Googling',
  'Reasons Your Phone Battery Is At 12%',
  'Things That Get Awkward In Elevators',
  'Foods That Sound Fancy But Aren’t',
  'Things That Are Impossible To Fold Correctly',
  'Signs A Restaurant Is About To Disappoint You',
  'Things Your Pet Judges You For',
  'Reasons To Pretend You’re Asleep',
  'Things That Are Funnier In Theory Than In Practice',
  'Celebrities Who Seem Like They Have A Secret Podcast',
  'Things That Should Not Come In Family Size',
  'Signs Someone Grew Up Without Siblings',
  'Things That Are Weirdly Hard To Say Out Loud',
  'Reasons A Road Trip Goes Wrong',
  'Things You’d Find In A Suspicious Junk Drawer',
  'Animals That Would Make Terrible Roommates',
  'Things That Are Somehow A Whole Personality',
  'Foods That Are Better As Leftovers',
  'Signs You’re About To Get Fired (Kidding, Mostly)',
  'Things That Make A Meeting Instantly Worse',
  'Reasons To Fake An Accent',
  'Things That Are Illegal In At Least One Country',
  'Celebrities Who’d Win A Staring Contest',
  'Things That Get Weird When You Say Them Too Many Times',
  'Signs Your Group Chat Has Gone Too Far',
  'Things You’d Regret Naming A Pet',
  'Foods That Cause Instant Regret',
  'Things That Are Scarier Than A Horror Movie',
  'Reasons Someone Cancels A First Date',
  'Things That Should Not Be A Competitive Sport (But Are)',
  'Signs You’re Turning Into Your Parents',
  'Things That Are Way Too Expensive For What They Are',
  'Celebrities Who Seem Like They’d Cry At Weddings',
  'Things You’d Never Say To A Cop',
  'Foods That Sound Made Up',
  'Things That Get Ruined By A Bad Sequel',
  'Reasons To Leave A Restaurant Immediately',
  'Things That Are Suspiciously Good At Multitasking',
  'Signs A Vacation Is About To Go Sideways',
  'Things You’d Never Wear In Public',
  'Celebrities Who Seem Like Bad Texters',
  'Things That Are Weirdly Nostalgic',
  'Foods That Should Never Be Microwaved',
  'Things That Get More Annoying With Age',
  'Reasons A Wedding Toast Goes Off The Rails',
  'Things That Are Impressively Petty',
  'Signs Someone Is Definitely Lying',
  'Things You’d Panic-Buy In An Emergency',
  'Celebrities Who Seem Like They Own Too Many Candles',
  'Things That Are Weirdly Hard To Throw Away',
  'Foods That Taste Better Stolen Off Someone Else’s Plate',
  'Things That Get Instantly Awkward At Family Dinner',
  'Reasons To Ghost A Group Project',
  'Things That Should Come With A Countdown Timer',
  'Signs You’ve Officially Become An Adult',
  'Things You’d Never Trust A Stranger With',
  'Celebrities Who’d Make Great Villains',
  'Things That Are Somehow Always Sticky',
  'Foods That Are A Trap',
  'Things That Get Weirdly Competitive At Family Game Night',
  'Reasons Someone Blocks You',
  'Things That Are Deceptively Expensive',
  'Signs A Movie Is Going To Be Bad',
  'Things You’d Bring To Prove You’re An Adult',
  'Celebrities Who Seem Like They’d Ghost You',
  'Things That Are Way Too Loud For 7AM',
  'Foods That Are Basically A Personality Trait',
  'Things That Get Ruined By Overthinking',
  'Reasons A Group Trip Falls Apart',
  'Things That Should Not Exist But Do',
  'Signs You’re The Villain In Someone Else’s Story',
  'Things You’d Never Say In A Job Interview',
  'Celebrities Who Seem Like They’d Steal Your Fries',
  'Things That Are Weirdly Hard To Compliment',
  'Foods That Are Only Good At 2 AM',
  'Things That Get Instantly Suspicious In A Text',
  'Reasons To Fake Being Sick',
  'Things That Are Somehow Both Cute And Terrifying',
  'Signs Someone Has Never Had A Pet',
  'Things You’d Never Let A Toddler Near',
  'Celebrities Who Seem Like They Meal Prep',
  'Things That Are Weirdly Hard To Whisper',
  'Foods That Ruin A Perfectly Good Sandwich',
  'Things That Get Way Too Serious At Trivia Night',
  'Reasons Someone Shows Up Late To Everything',
  'Things That Should Come With A Manual',
  'Signs A Neighbor Is Up To Something',
  'Things You’d Never Do On A First Date',
  'Celebrities Who Seem Like They’d Win At Karaoke',
  'Things That Are Weirdly Comforting',
  'Foods That Sound Healthy But Aren’t',
  'Things That Get Ruined By A Bad Playlist',
  'Reasons To Avoid Eye Contact',
  'Things That Are Suspiciously Cheap',
  'Signs You’ve Been On Your Phone Too Long',
  'Things You’d Never Admit At A Family Reunion',
  'Celebrities Who’d Be Terrible At Poker',
  'Things That Are Weirdly Hard To Pack',
  'Foods That Taste Like A Bad Decision',
  'Things That Get Instantly Awkward On A Zoom Call',
  'Reasons A Roommate Situation Ends Badly',
  'Things That Should Not Be This Complicated',
  'Signs Someone Is A Morning Person (Unfortunately)',
  'Things You’d Never Trust In A Gas Station',
  'Celebrities Who Seem Like They’d Overtip',
  'Things That Are Weirdly Specific To Grow Up With',
  'Things That Get Ruined By A Bad Wifi Connection',
  'Reasons Someone Might Fake A Text Emergency',
  'Things That Are Scarier At A Sleepover Than At Home',
  'Signs A Gym Membership Was A Mistake',
  'Things You’d Never Say To Airport Security',
  'Celebrities Who Seem Like They’d Cheat At Board Games',
  'Foods That Are Just A Vehicle For Butter',
  'Things That Get Weirdly Emotional At A Graduation',
  'Reasons A Camping Trip Goes Wrong',
  'Things That Should Not Be Whispered In Public',
  'Signs Someone Grew Up As The Favorite Child',
  'Things You’d Never Bring To A Job Interview',
  'Celebrities Who Seem Like They’d Overpack',
  'Things That Are Weirdly Hard To Explain To A Kid',
  'Foods That Get Weird If You Think About Them Too Long',
  'Things That Get Ruined By A Bad Haircut',
  'Reasons To Avoid The Office Kitchen',
  'Things That Should Not Be A Group Activity',
  'Signs You’re About To Regret A Purchase',
  'Things You’d Never Do At A Funeral',
  'Celebrities Who Seem Like They’d Be Rude To Waiters',
  'Things That Are Weirdly Competitive Between Siblings',
  'Foods That Are Suspiciously Good For The Price',
  'Things That Get Instantly Ruined By A Typo',
  'Reasons Someone Avoids The Family Group Chat',
  'Things That Should Not Be A Whole Personality (But Are)',
  'Signs A Coworker Is About To Quit',
  'Things You’d Never Trust A Toddler With',
  'Celebrities Who Seem Like They’d Be Bad At Camping',
  'Things That Are Weirdly Hard To Say With A Straight Face',
  'Foods That Get Better The Sketchier The Place Looks',
  'Things That Get Ruined By Bad Lighting',
  'Reasons A First Day Of Work Goes Badly',
  'Things That Should Not Be Allowed On Public Transit',
  'Signs Someone Is A Middle Child',
  'Things You’d Never Say To Your Landlord',
  'Celebrities Who Seem Like They’d Own A Weird Amount Of Hats',
  'Things That Are Weirdly Stressful To Buy',
  'Foods That Taste Better When Someone Else Cooks Them',
  'Things That Get Ruined By An Overzealous Autocorrect',
  'Reasons A Group Photo Takes Forever',
  'Things That Should Not Be This Hard To Assemble',
  'Signs You’re About To Get Roped Into An MLM',
  'Things You’d Never Admit To A Therapist (But Should)',
  'Celebrities Who Seem Like They’d Get Lost Easily',
  'Things That Are Weirdly Hard To Return',
  'Foods That Are A Personality Test In Disguise',
  'Things That Get Ruined By A Bad Group Chat Name',
  'Reasons To Skip A High School Reunion',
  'Things That Should Not Be This Loud At 6 AM',
  'Signs A Blind Date Is Going Badly',
  'Things You’d Never Say During A Job Performance Review',
  'Celebrities Who Seem Like They’d Steal The Aux Cord',
  'Things That Are Weirdly Hard To Whisper-Sing',
  'Foods That Should Come With A Disclaimer',
  'Things That Get Ruined By A Bad Sequel Announcement',
  'Reasons A DIY Project Goes Wrong',
  'Things That Should Not Be Sold In A Vending Machine',
  'Signs You’ve Officially Peaked In College',
  'Things You’d Never Trust At A Garage Sale',
  'Celebrities Who Seem Like They’d Be Loud Chewers',
  'Things That Are Weirdly Competitive At A Potluck',
  'Foods That Get Ruined By Overthinking The Recipe',
  'Things That Get Instantly Awkward At A Baby Shower',
  'Reasons Someone Avoids Answering Their Phone',
  'Things That Should Not Be A Bachelor Party Tradition',
  'Signs A Roommate Interview Went Badly',
  'Things You’d Never Say While Getting A Haircut',
  'Celebrities Who Seem Like They’d Be Bad At Charades',
  'Things That Are Weirdly Hard To Regift',
  'Foods That Are Only Acceptable As A Dare',
  'Things That Get Ruined By A Bad Group Costume Idea',
  'Reasons A Class Reunion Gets Awkward',
  'Things That Should Not Be This Complicated To Cancel',
  'Signs You’re The Group’s Designated Planner',
  'Things You’d Never Admit To Your Dentist',
  'Celebrities Who Seem Like They’d Hog The Blanket',
  'Things That Are Weirdly Hard To Say No To',
  'Foods That Are Better With A Weird Amount Of Sauce',
  'Things That Get Ruined By A Bad Group Vote',
  'Reasons A House Party Ends Early',
  'Things That Should Not Be A Family Heirloom',
  'Signs Someone Is About To Overshare',
  'Things You’d Never Do In A Shared Office Fridge',
  'Celebrities Who Seem Like They’d Cry During A Commercial',
  'Things That Are Weirdly Hard To Un-Hear',
  'Foods That Taste Wrong Once You Know What’s In Them',
  'Things That Get Ruined By A Bad Nickname',
  'Reasons Someone Skips Their Own Birthday Party',
  'Things That Should Not Be This Stressful To Parallel Park',
  'Signs A Group Costume Idea Was A Mistake',
  'Things You’d Never Say In A Wedding Speech',
  'Celebrities Who Seem Like They’d Be Great At Escape Rooms',
  'Things That Are Weirdly Hard To Apologize For',
  'Foods That Are Only Good If Someone Else Buys Them',
  'Things That Get Ruined By A Bad Group Nickname',
  'Reasons A Family Vacation Ends In An Argument',
  'Worst Gifts To Get Someone You Just Started Dating',
  'Apps You’re Embarrassed To Have On Your Phone',
  'Things You’d Find In A Time Capsule From 2005',
  'Signs A Yelp Review Is Fake',
  'Objects That Deserve Their Own National Holiday',
  'Group Chat Names That Are Secretly A Red Flag',
  'Things That Ruin A Perfectly Good Nap',
  'Things A Raccoon Would Definitely Steal',
  'Sounds A Haunted House Doesn’t Actually Need',
  'Excuses For Not Going To The Gym',
  'Things That Make An Uber Ride Awkward',
  'Signs Your Smart Home Has A Mind Of Its Own',
  'Things You’d Overhear At A Farmers Market',
  'Things That Make A Hotel Room Feel Sketchy',
  'Signs A Recipe Is Lying To You',
  'Things That Are Cursed If You Own Too Many',
  'Objects That Would Win A Staring Contest',
  'Things That Are Suspicious In A Stranger’s Fridge',
  'Careers That Sound Cooler Than They Actually Are',
  'Things Overheard In A Waiting Room',
  'Signs A Group Trip Was Planned By The Wrong Person',
  'Items That Should Come With A Bodyguard',
  'Things That Get Weirdly Sentimental With Age',
  'Reasons A Garage Sale Gets Heated',
  'Things You’d Bribe A Toddler With',
  'Signs Someone Peaked At Their Own Birthday Party',
  'Things That Are Funnier When A Kid Says Them',
  'Objects That Have No Business Being This Heavy',
  'Things That Get Ruined By A Bad Group Photo Timing',
  'Reasons To Suspect A Coworker Is Job Hunting',
  'Things You’d Never Trust A Weather App On',
  'Signs A Potluck Dish Is A Mystery For A Reason',
  'Things That Sound Made Up At The DMV',
  'Reasons A Camping Trip Ends Early',
  'Things You’d Regret Bringing To Karaoke',
  'Signs Someone’s Never Done Laundry Before',
  'Objects That Should Not Be A Family Tradition',
  'Things That Get Weirdly Competitive At A Yard Sale',
  'Reasons Your Package Says "Delivered" But Isn’t',
  'Things That Are Scarier Than A Dentist Appointment',
  'Signs A Group Chat Poll Was A Bad Idea',
  'Things You’d Never Say To A Barber Mid-Haircut',
  'Reasons A Board Game Night Ends A Friendship',
  'Things That Make A Grocery Store Trip Take Forever',
  'Signs Someone’s Lying About Their Commute Time',
  'Objects That Are Weirdly Hard To Gift Wrap',
  'Things That Get Ruined By A Bad Group Rename',
  'Reasons To Distrust A "Gently Used" Listing',
  'Things You’d Never Admit To A Barista',
  'Signs A Neighbor’s Renovation Has Gone On Too Long',
  'Things That Are Suspiciously Loud At 3AM',
  'Reasons A Group Selfie Takes Twelve Tries',
  'Things You’d Find In A Suspiciously Organized Junk Drawer',
  'Signs Someone’s About To Pitch You An MLM',
  'Objects That Should Come With A Consent Form',
  'Things That Get Weird If You Stare At Them Too Long',
  'Reasons A Thermostat Argument Never Ends',
  'Things You’d Never Trust A Fortune Cookie To Say',
  'Signs A Wifi Password Is Testing Your Patience',
  'Things That Make A Parent-Teacher Conference Awkward',
  'Reasons To Fake An Emergency Exit From A Party',
  'Things You’d Never Whisper To A Psychic',
  'Signs A Group Vacation Rental Photo Lied To You',
  'Objects That Are A Personality Test In A Garage',
  'Things That Get Ruined By A Bad Group Playlist Vote',
  'Reasons A Text Thread Gets Left On Read',
  'Things You’d Never Say While Getting A Tattoo',
  'Signs Someone’s About To Regret A Bangs Decision',
  'Things That Make A Dog Park Interesting',
  'Reasons A Group Costume Falls Apart Last Minute',
  'Things You’d Never Trust A Vending Machine To Have',
  'Signs A Group Chat Has A Silent Reader Problem',
  'Objects That Are Weirdly Powerful For Their Size',
  'Things That Get Ruined By Reading The Reviews First',
  'Reasons To Suspect A Sale Isn’t Really A Sale',
  'Things You’d Never Say During A Massage',
  'Signs A Group Photo Op Is About To Go Wrong',
  'Things That Make An Airport Layover Interesting',
  'Reasons A Group Chat Argument Starts Over Nothing',
  'Things You’d Never Trust A Toddler To Explain',
  'Signs Someone’s About To Overshare At Book Club',
  'Objects That Should Not Be This Hard To Open',
  'Things That Get Weird When You Say Them In A Meeting',
  'Reasons A Group Vacation Budget Falls Apart',
  'Things You’d Never Admit To Loving Unironically',
  'Signs A Recipe Video Skipped A Step On Purpose',
  'Things That Make A Waiting Room TV Worse',
  'Reasons To Suspect A Contractor Is Winging It',
  'Things You’d Never Trust A Magic 8 Ball To Answer',
  'Signs Someone’s About To Tell A Long Story',
  'Objects That Are Weirdly Emotional To Throw Away',
  'Things That Get Ruined By A Bad First Impression',
  'Reasons A Group Chat Goes Quiet After One Message',
  'Things You’d Never Say To A Substitute Teacher',
  'Signs A DIY Haircut Was A Mistake',
  'Things That Make A Long Car Ride Bearable',
  'Reasons A Group Text RSVP Never Comes',
  'Things You’d Never Trust A Carnival Game To Be Fair About',
  'Signs Someone’s About To Ask For A Favor',
  'Objects That Deserve A Warning Label But Don’t Have One',
  'Things That Get Weird At A Company Holiday Party',
  'Reasons A Group Chat Debate Gets Personal',
  'Things You’d Never Say On A First Day Of School',
  'Signs A Thrift Store Find Has A Story Behind It',
  'Things That Make A Long Layover Feel Longer',
  'Reasons A Group Photo Never Gets Sent To Everyone',
  'Things You’d Never Trust An Infomercial To Show Accurately',
];
