// Original BuzzFeed-listicle-style categories, written fresh for this app
// (not transcribed from any physical game's card text).
export const CATEGORIES: string[] = [
  'Hot Dads',
  'Things That Deserve A Round Of Applause Just For Existing',
  'Celebrities You’d Let Ruin Your Life',
  'Insults That Don’t Contain A Curse Word',
  'Random Things That Are Weirdly Addictive',
  'Times A Celebrity Was Actually Your Favorite Person',
  'Questions You’re Too Afraid To Ask',
  'Movie Plot Holes That Still Bother Us',
  'Things That Are Somehow Still Legal',
  'Signs You Peaked In High School',
  'Foods That Are Better Cold Than Hot',
  'Things Nobody Asked For But We Got Anyway',
  'Excuses That Never Actually Work',
  'Things That Get Weirdly Competitive',
  'Objects That Should Not Be Sentient But Kind Of Are',
  'Things You’d Bring To A Deserted Island For No Reason',
  'Reasons To Leave A Group Chat',
  'Things That Sound Fake But Are Real',
  'Celebrities Who Seem Like They’d Give Bad Advice',
  'Things That Peaked In The 2000s',
  'Jobs That Sound Made Up',
  'Things That Are Weirdly Satisfying To Watch',
  'Reasons Someone Might Ghost You',
  'Things That Are Only Acceptable On Vacation',
  'Animals That Would Win In A Fight Against A Toddler',
  'Things That Are Secretly A Personality Type',
  'Snacks That Cause Arguments',
  'Things You’d Regret Saying In A Toast',
  'Household Items That Could Be Weapons In A Pinch',
  'Things That Are Somehow Both Impressive And Sad',
  'Reasons To Fake A Phone Call',
  'Things That Get Ruined By Overexplaining',
  'Celebrities Who Seem Like Bad Roommates',
  'Things That Are Way Scarier Than They Should Be',
  'Signs Someone Is About To Do Something Dumb',
  'Things That Should Come With A Warning Label',
  'Foods That Don’t Deserve Their Reputation',
  'Things That Are Impressive For The Wrong Reasons',
  'Reasons A Party Actually Ends',
  'Things That Are Way More Complicated Than They Look',
  'Objects That Have Definitely Been Used As A Weapon In A Movie',
  'Things That Instantly Age You',
  'Words That Sound Made Up But Aren’t',
  'Things That Are Suspiciously Specific',
  'Reasons Not To Trust Someone',
  'Things That Are Only Funny At 2AM',
  'Celebrities Who Could Probably Beat You Up',
  'Things That Are A Red Flag On A First Date',
  'Places You’d Hide If Something Chased You',
  'Things People Lie About On Dating Apps',
  'Sounds That Instantly Stress You Out',
  'Things That Are Deceptively Difficult',
  'Reasons To Cancel Plans Last Minute',
  'Things That Are Weirdly Emotional For No Reason',
  'Celebrities Who’d Be Terrible At Parenting',
  'Things That Are Impossible To Do Quietly',
  'Objects That Are Scarier In The Dark',
  'Things That Should Be Illegal But Aren’t',
  'Reasons A Group Project Falls Apart',
  'Things That Get Better With Age (Besides Wine)',
  'Signs You’re The Problem In The Group Chat',
  'Things That Are Wildly Overpriced For No Reason',
  'Foods That Are Just An Excuse To Eat Sauce',
  'Things That Are Way Louder Than They Need To Be',
  'Celebrities Who Seem Like They Smell Like Money',
  'Things You’d Never Admit To Googling',
  'Reasons Your Phone Battery Is At 12%',
  'Things That Get Awkward In Elevators',
  'Foods That Sound Fancy But Aren’t',
  'Things That Are Impossible To Fold Correctly',
  'Signs A Restaurant Is About To Disappoint You',
  'Things Your Pet Judges You For',
  'Reasons To Pretend You’re Asleep',
  'Things That Are Funnier In Theory Than In Practice',
  'Celebrities Who Seem Like They Have A Secret Podcast',
  'Things That Should Not Come In Family Size',
  'Signs Someone Grew Up Without Siblings',
  'Things That Are Weirdly Hard To Say Out Loud',
  'Reasons A Road Trip Goes Wrong',
  'Things You’d Find In A Suspicious Junk Drawer',
  'Animals That Would Make Terrible Roommates',
  'Things That Are Somehow A Whole Personality',
  'Foods That Are Better As Leftovers',
  'Signs You’re About To Get Fired (Kidding, Mostly)',
  'Things That Make A Meeting Instantly Worse',
  'Reasons To Fake An Accent',
  'Things That Are Illegal In At Least One Country',
  'Celebrities Who’d Win A Staring Contest',
  'Things That Get Weird When You Say Them Too Many Times',
  'Signs Your Group Chat Has Gone Too Far',
  'Things You’d Regret Naming A Pet',
  'Foods That Cause Instant Regret',
  'Things That Are Scarier Than A Horror Movie',
  'Reasons Someone Cancels A First Date',
  'Things That Should Not Be A Competitive Sport (But Are)',
  'Signs You’re Turning Into Your Parents',
  'Things That Are Way Too Expensive For What They Are',
  'Celebrities Who Seem Like They’d Cry At Weddings',
  'Things You’d Never Say To A Cop',
  'Foods That Sound Made Up',
  'Things That Get Ruined By A Bad Sequel',
  'Reasons To Leave A Restaurant Immediately',
  'Things That Are Suspiciously Good At Multitasking',
  'Signs A Vacation Is About To Go Sideways',
  'Things You’d Never Wear In Public',
  'Celebrities Who Seem Like Bad Texters',
  'Things That Are Weirdly Nostalgic',
  'Foods That Should Never Be Microwaved',
  'Things That Get More Annoying With Age',
  'Reasons A Wedding Toast Goes Off The Rails',
  'Things That Are Impressively Petty',
  'Signs Someone Is Definitely Lying',
  'Things You’d Panic-Buy In An Emergency',
  'Celebrities Who Seem Like They Own Too Many Candles',
  'Things That Are Weirdly Hard To Throw Away',
  'Foods That Taste Better Stolen Off Someone Else’s Plate',
  'Things That Get Instantly Awkward At Family Dinner',
  'Reasons To Ghost A Group Project',
  'Things That Should Come With A Countdown Timer',
  'Signs You’ve Officially Become An Adult',
  'Things You’d Never Trust A Stranger With',
  'Celebrities Who’d Make Great Villains',
  'Things That Are Somehow Always Sticky',
  'Foods That Are A Trap',
  'Things That Get Weirdly Competitive At Family Game Night',
  'Reasons Someone Blocks You',
  'Things That Are Deceptively Expensive',
  'Signs A Movie Is Going To Be Bad',
  'Things You’d Bring To Prove You’re An Adult',
  'Celebrities Who Seem Like They’d Ghost You',
  'Things That Are Way Too Loud For 7AM',
  'Foods That Are Basically A Personality Trait',
  'Things That Get Ruined By Overthinking',
  'Reasons A Group Trip Falls Apart',
  'Things That Should Not Exist But Do',
  'Signs You’re The Villain In Someone Else’s Story',
  'Things You’d Never Say In A Job Interview',
  'Celebrities Who Seem Like They’d Steal Your Fries',
  'Things That Are Weirdly Hard To Compliment',
  'Foods That Are Only Good At 2 AM',
  'Things That Get Instantly Suspicious In A Text',
  'Reasons To Fake Being Sick',
  'Things That Are Somehow Both Cute And Terrifying',
  'Signs Someone Has Never Had A Pet',
  'Things You’d Never Let A Toddler Near',
  'Celebrities Who Seem Like They Meal Prep',
  'Things That Are Weirdly Hard To Whisper',
  'Foods That Ruin A Perfectly Good Sandwich',
  'Things That Get Way Too Serious At Trivia Night',
  'Reasons Someone Shows Up Late To Everything',
  'Things That Should Come With A Manual',
  'Signs A Neighbor Is Up To Something',
  'Things You’d Never Do On A First Date',
  'Celebrities Who Seem Like They’d Win At Karaoke',
  'Things That Are Weirdly Comforting',
  'Foods That Sound Healthy But Aren’t',
  'Things That Get Ruined By A Bad Playlist',
  'Reasons To Avoid Eye Contact',
  'Things That Are Suspiciously Cheap',
  'Signs You’ve Been On Your Phone Too Long',
  'Things You’d Never Admit At A Family Reunion',
  'Celebrities Who’d Be Terrible At Poker',
  'Things That Are Weirdly Hard To Pack',
  'Foods That Taste Like A Bad Decision',
  'Things That Get Instantly Awkward On A Zoom Call',
  'Reasons A Roommate Situation Ends Badly',
  'Things That Should Not Be This Complicated',
  'Signs Someone Is A Morning Person (Unfortunately)',
  'Things You’d Never Trust In A Gas Station',
  'Celebrities Who Seem Like They’d Overtip',
  'Things That Are Weirdly Specific To Grow Up With',
];
